#!/usr/bin/env bash
#
# Inv-Keep interactive installer.
# Prompts for hostname / port / SSL / email / OIDC, writes .env, and starts the
# stack with Docker Compose (optionally with the automatic-HTTPS Caddy proxy).
#
# Usage:  ./install.sh            (interactive)
#         ./install.sh -y         (accept defaults, no prompts)
#
set -euo pipefail

cd "$(dirname "$0")"

BOLD=$'\033[1m'; DIM=$'\033[2m'; GREEN=$'\033[32m'; YELLOW=$'\033[33m'; RED=$'\033[31m'; RESET=$'\033[0m'
say()  { printf "%s\n" "$*"; }
ok()   { printf "${GREEN}✓${RESET} %s\n" "$*"; }
warn() { printf "${YELLOW}!${RESET} %s\n" "$*"; }
die()  { printf "${RED}✗ %s${RESET}\n" "$*" >&2; exit 1; }

ASSUME_YES=0
[ "${1:-}" = "-y" ] && ASSUME_YES=1

ask() { # ask "Prompt" "default" -> echoes answer
  local prompt="$1" def="${2:-}" ans=""
  if [ "$ASSUME_YES" = "1" ]; then printf "%s" "$def"; return; fi
  if [ -n "$def" ]; then read -r -p "$prompt [$def]: " ans || true; else read -r -p "$prompt: " ans || true; fi
  printf "%s" "${ans:-$def}"
}
ask_secret() { # ask_secret "Prompt" -> echoes answer (hidden)
  local prompt="$1" ans=""
  if [ "$ASSUME_YES" = "1" ]; then printf ""; return; fi
  read -r -s -p "$prompt: " ans || true; echo >&2
  printf "%s" "$ans"
}
yesno() { # yesno "Question" "y|n" -> returns 0 for yes
  local def="${2:-n}" ans; ans="$(ask "$1 (y/n)" "$def")"
  case "$ans" in [Yy]*) return 0;; *) return 1;; esac
}

gen_secret() {
  if command -v openssl >/dev/null 2>&1; then openssl rand -hex 32
  elif command -v python3 >/dev/null 2>&1; then python3 -c "import secrets;print(secrets.token_hex(32))"
  else head -c 32 /dev/urandom | od -An -tx1 | tr -d ' \n'; fi
}

# --- compose command detection ---
COMPOSE=""
if docker compose version >/dev/null 2>&1; then COMPOSE="docker compose"
elif command -v docker-compose >/dev/null 2>&1; then COMPOSE="docker-compose"
fi

say ""
say "${BOLD}Inv-Keep installer${RESET}"
say "${DIM}This writes .env and starts the app with Docker Compose.${RESET}"
say ""

command -v docker >/dev/null 2>&1 || warn "Docker not found on PATH — install Docker Desktop / Engine before starting the stack."
[ -n "$COMPOSE" ] || warn "Docker Compose not found — you can still write .env now and run compose later."

# --- existing .env guard ---
if [ -f .env ] && [ "$ASSUME_YES" != "1" ]; then
  yesno "A .env already exists. Overwrite it?" "n" || die "Aborted; existing .env kept."
fi

# --- gather config ---
say "${BOLD}1) Hostname & access${RESET}"
HOSTNAME_IN="$(ask "Public hostname (domain or IP)" "localhost")"
APP_PORT="$(ask "Host port for direct access" "8000")"

USE_SSL=1
if yesno "Enable automatic HTTPS (Let's Encrypt via Caddy)?" "n"; then USE_SSL=1; else USE_SSL=0; fi
ACME_EMAIL="admin@example.com"
if [ "$USE_SSL" = "1" ]; then
  case "$HOSTNAME_IN" in
    localhost|127.0.0.1|"") warn "SSL needs a real public domain with DNS + ports 80/443. 'localhost' won't get a cert.";;
  esac
  ACME_EMAIL="$(ask "Email for Let's Encrypt notices" "admin@${HOSTNAME_IN}")"
  SCHEME="https"; BASE_URL="https://${HOSTNAME_IN}"
else
  SCHEME="http"; BASE_URL="http://${HOSTNAME_IN}:${APP_PORT}"
fi

say ""
say "${BOLD}2) Branding${RESET}"
APP_TITLE="$(ask "App title" "Inv-Keep")"
CURRENCY="$(ask "Currency symbol" "$")"

say ""
say "${BOLD}3) Authentication (Authentik / OIDC)${RESET}"
AUTH_MODE="none"; OIDC_DISCOVERY=""; OIDC_CLIENT_ID=""; OIDC_CLIENT_SECRET=""; OIDC_REDIRECT=""
if yesno "Configure OIDC login now?" "n"; then
  AUTH_MODE="oidc"
  OIDC_DISCOVERY="$(ask "OIDC discovery URL" "https://auth.${HOSTNAME_IN}/application/o/inv-keep/.well-known/openid-configuration")"
  OIDC_CLIENT_ID="$(ask "OIDC client ID" "")"
  OIDC_CLIENT_SECRET="$(ask_secret "OIDC client secret")"
  OIDC_REDIRECT="${BASE_URL}/auth/callback"
  ok "Register this redirect URI in your IdP: ${OIDC_REDIRECT}"
fi

SESSION_SECRET="$(gen_secret)"

# --- write .env ---
say ""
say "${BOLD}Writing .env …${RESET}"
{
  echo "# Generated by install.sh on $(date -u +%Y-%m-%dT%H:%M:%SZ)"
  echo "DATABASE_URL=sqlite:////code/data/app.db"
  echo "SESSION_SECRET=${SESSION_SECRET}"
  echo ""
  echo "HOSTNAME=${HOSTNAME_IN}"
  echo "APP_PORT=${APP_PORT}"
  echo "ACME_EMAIL=${ACME_EMAIL}"
  echo ""
  echo "APP_TITLE=${APP_TITLE}"
  echo "CURRENCY=${CURRENCY}"
  echo ""
  echo "AUTH_MODE=${AUTH_MODE}"
  echo "OIDC_DISCOVERY_URL=${OIDC_DISCOVERY}"
  echo "OIDC_CLIENT_ID=${OIDC_CLIENT_ID}"
  echo "OIDC_CLIENT_SECRET=${OIDC_CLIENT_SECRET}"
  echo "OIDC_REDIRECT_URL=${OIDC_REDIRECT}"
} > .env
chmod 600 .env
ok ".env written (mode 600)."

mkdir -p data

# --- start ---
say ""
START_HINT="docker compose up -d --build"
[ "$USE_SSL" = "1" ] && START_HINT="docker compose --profile ssl up -d --build"

if [ -z "$COMPOSE" ]; then
  warn "Docker Compose not available; skipping startup."
  say "Run later:  ${BOLD}${START_HINT}${RESET}"
  exit 0
fi

if yesno "Build and start Inv-Keep now?" "y"; then
  if [ "$USE_SSL" = "1" ]; then
    say "Starting with automatic HTTPS (Caddy)…"
    $COMPOSE --profile ssl up -d --build
  else
    $COMPOSE up -d --build
  fi
  ok "Inv-Keep is starting."
  say ""
  say "Open:  ${BOLD}${BASE_URL}${RESET}"
  [ "$AUTH_MODE" = "oidc" ] && say "Login via your IdP. Break-glass if locked out: set DISABLE_AUTH=1 in .env and restart."
  say "Configure email, alerts, branding and label sizes under Settings."
else
  say "Skipped startup. Start later with:"
  if [ "$USE_SSL" = "1" ]; then say "  ${BOLD}$COMPOSE --profile ssl up -d --build${RESET}"; else say "  ${BOLD}$COMPOSE up -d --build${RESET}"; fi
fi
