from datetime import datetime

from sqlalchemy import (
    Boolean,
    Column,
    DateTime,
    Float,
    ForeignKey,
    Integer,
    Numeric,
    String,
    Text,
    UniqueConstraint,
)
from sqlalchemy.orm import relationship

from .database import Base


class Setting(Base):
    """Simple key/value store for UI-configurable settings."""

    __tablename__ = "settings"

    key = Column(String, primary_key=True)
    value = Column(Text, default="")


class Category(Base):
    __tablename__ = "categories"

    id = Column(Integer, primary_key=True)
    name = Column(String, nullable=False)
    description = Column(Text, default="")
    parent_id = Column(Integer, ForeignKey("categories.id"), nullable=True)
    created_at = Column(DateTime, default=datetime.utcnow)

    parent = relationship("Category", remote_side=[id], backref="children")


class Part(Base):
    __tablename__ = "parts"

    id = Column(Integer, primary_key=True)
    name = Column(String, nullable=False)
    description = Column(Text, default="")
    icon = Column(String, default="")   # emoji / short text for quick identification
    image = Column(String, default="")  # optional uploaded photo path (/uploads/items/..)
    barcode = Column(String, unique=True, nullable=False, index=True)
    # "bulk"  -> quantity-tracked SKU, one barcode shared by many identical items
    # "unique"-> a single physical item with its own barcode
    type = Column(String, nullable=False, default="bulk")
    unit_cost = Column(Numeric(10, 2), nullable=False, default=0)   # what the item costs us
    unit_price = Column(Numeric(10, 2), nullable=False, default=0)  # what we charge the client
    quantity_on_hand = Column(Integer, nullable=False, default=0)
    category_id = Column(Integer, ForeignKey("categories.id"), nullable=True)
    # Per-part override; None falls back to the global default threshold.
    low_stock_threshold = Column(Integer, nullable=True)
    low_stock_alerted = Column(Boolean, nullable=False, default=False)
    # True when the barcode was generated by us (printable label available).
    barcode_generated = Column(Boolean, nullable=False, default=False)
    active = Column(Boolean, nullable=False, default=True)
    # Hidden from the catalog list by default. Used for ad-hoc / custom items
    # logged at charge-out time (e.g. parts bought at a hardware store in the
    # field). Still queryable and reusable, just out of the way.
    archived = Column(Boolean, nullable=False, default=False)
    created_at = Column(DateTime, default=datetime.utcnow)

    category = relationship("Category")


class Client(Base):
    # Table stays "customers" so existing data upgrades in place.
    __tablename__ = "customers"

    id = Column(Integer, primary_key=True)
    name = Column(String, nullable=False)
    reference = Column(String, default="")  # account / customer number
    contact_name = Column(String, default="")
    email = Column(String, default="")
    phone = Column(String, default="")
    location = Column(String, default="")  # site / building / room
    address = Column(Text, default="")
    notes = Column(Text, default="")
    active = Column(Boolean, nullable=False, default=True)
    # Hidden from the main /clients list by default. Used for walk-in /
    # one-time-purchase clients created from the cart card without polluting
    # the recurring-client roster (mirror of Part.archived).
    archived = Column(Boolean, nullable=False, default=False)
    created_at = Column(DateTime, default=datetime.utcnow)

    jobs = relationship("Job", back_populates="client", order_by="Job.name")


class Job(Base):
    __tablename__ = "jobs"

    id = Column(Integer, primary_key=True)
    client_id = Column(Integer, ForeignKey("customers.id"), nullable=False)
    name = Column(String, nullable=False)
    reference = Column(String, default="")  # ticket / work-order number
    notes = Column(Text, default="")
    active = Column(Boolean, nullable=False, default=True)
    created_at = Column(DateTime, default=datetime.utcnow)

    client = relationship("Client", back_populates="jobs")


class Location(Base):
    """A physical place where stock is kept — e.g. the office, a truck, or
    a job-site cage. Stock is counted per-location via StockLevel; Part's
    `quantity_on_hand` stays as the sum across all locations so older
    pages / reports keep working unchanged."""

    __tablename__ = "locations"

    id = Column(Integer, primary_key=True)
    name = Column(String, unique=True, nullable=False)
    notes = Column(Text, default="")
    active = Column(Boolean, nullable=False, default=True)
    archived = Column(Boolean, nullable=False, default=False)
    created_at = Column(DateTime, default=datetime.utcnow)


class StockLevel(Base):
    """How many of a given Part are kept at a given Location. One row per
    (part, location) pair."""

    __tablename__ = "stock_levels"
    __table_args__ = (
        UniqueConstraint("part_id", "location_id", name="uq_stock_part_loc"),
    )

    id = Column(Integer, primary_key=True)
    part_id = Column(Integer, ForeignKey("parts.id"), nullable=False, index=True)
    location_id = Column(Integer, ForeignKey("locations.id"), nullable=False, index=True)
    quantity = Column(Integer, nullable=False, default=0)

    part = relationship("Part")
    location = relationship("Location")


class Transfer(Base):
    """An atomic stock movement between two Locations. Created in one shot;
    completing it decrements the source StockLevels and increments the
    destination's. Status stays at 'completed' once posted — voiding a
    transfer is a follow-up scope."""

    __tablename__ = "transfers"

    id = Column(Integer, primary_key=True)
    from_location_id = Column(Integer, ForeignKey("locations.id"), nullable=False)
    to_location_id = Column(Integer, ForeignKey("locations.id"), nullable=False)
    status = Column(String, nullable=False, default="completed", index=True)
    created_by = Column(String, default="")
    notes = Column(Text, default="")
    created_at = Column(DateTime, default=datetime.utcnow)
    completed_at = Column(DateTime, nullable=True)

    from_location = relationship("Location", foreign_keys=[from_location_id])
    to_location = relationship("Location", foreign_keys=[to_location_id])
    lines = relationship("TransferLine", back_populates="transfer",
                         cascade="all, delete-orphan", order_by="TransferLine.id")


class TransferLine(Base):
    __tablename__ = "transfer_lines"

    id = Column(Integer, primary_key=True)
    transfer_id = Column(Integer, ForeignKey("transfers.id"), nullable=False, index=True)
    part_id = Column(Integer, ForeignKey("parts.id"), nullable=False)
    quantity = Column(Integer, nullable=False, default=0)

    transfer = relationship("Transfer", back_populates="lines")
    part = relationship("Part")


class Order(Base):
    """A charge-out cart that bundles one or more Transaction lines under a
    single order number. Lifecycle: open → submitted (number assigned) → may
    be voided. Stock is decremented as lines are scanned in (so concurrent
    techs can't oversell); cancelling an open cart voids the lines and
    restores stock."""

    __tablename__ = "orders"

    id = Column(Integer, primary_key=True)
    # Human-facing number, e.g. "ORD-202605-0001". Null while open; stamped
    # at submit time. Unique only across submitted orders.
    number = Column(String, unique=True, nullable=True, index=True)
    customer_id = Column(Integer, ForeignKey("customers.id"), nullable=True)
    job_id = Column(Integer, ForeignKey("jobs.id"), nullable=True)
    # Source location for every line scanned into this cart. May be changed
    # mid-cart; api_cart_set re-stamps existing lines so reporting stays clean.
    location_id = Column(Integer, ForeignKey("locations.id"), nullable=True, index=True)
    # open | submitted | voided | cancelled
    status = Column(String, nullable=False, default="open", index=True)
    created_by = Column(String, default="")            # username that opened it
    submitted_by = Column(String, default="")
    voided_by = Column(String, default="")
    voided_reason = Column(Text, default="")
    created_at = Column(DateTime, default=datetime.utcnow)
    submitted_at = Column(DateTime, nullable=True)
    voided_at = Column(DateTime, nullable=True)

    client = relationship("Client", foreign_keys=[customer_id])
    job = relationship("Job", foreign_keys=[job_id])
    location = relationship("Location", foreign_keys=[location_id])


class Transaction(Base):
    __tablename__ = "transactions"

    id = Column(Integer, primary_key=True)
    # Column name stays customer_id for data compatibility; it points at a Client.
    # Nullable so cart lines can exist before the user picks a client; submit
    # rejects an open cart without a client set, and /api/cart/set backfills
    # this column onto every line when the user picks one.
    customer_id = Column(Integer, ForeignKey("customers.id"), nullable=True)
    job_id = Column(Integer, ForeignKey("jobs.id"), nullable=True)
    part_id = Column(Integer, ForeignKey("parts.id"), nullable=False)
    # FK to the Order this line belongs to. Nullable for legacy rows that
    # predate the cart redesign.
    order_id = Column(Integer, ForeignKey("orders.id"), nullable=True, index=True)
    # Source location for the stock that fed this line — billed FROM here and
    # restored TO here on void. Nullable for legacy rows from before v1.15.
    location_id = Column(Integer, ForeignKey("locations.id"), nullable=True, index=True)
    quantity = Column(Integer, nullable=False, default=1)
    # Snapshots taken at charge-out time so later price edits never rewrite history.
    unit_cost_at_time = Column(Numeric(10, 2), nullable=False, default=0)   # our cost
    unit_price_at_time = Column(Numeric(10, 2), nullable=False, default=0)  # client charge
    scanned_by = Column(String, default="")
    note = Column(Text, default="")
    voided = Column(Boolean, nullable=False, default=False)
    created_at = Column(DateTime, default=datetime.utcnow)
    # Optional geolocation captured at charge-out time (audit / proof-of-presence).
    # Null when the browser denies the permission or the request times out.
    lat = Column(Float, nullable=True)
    lng = Column(Float, nullable=True)
    geo_accuracy_m = Column(Float, nullable=True)  # accuracy in metres, if reported

    part = relationship("Part")
    client = relationship("Client", foreign_keys=[customer_id])
    job = relationship("Job", foreign_keys=[job_id])
    order = relationship("Order")
    location = relationship("Location", foreign_keys=[location_id])

    @property
    def total_charge(self):
        return float(self.unit_price_at_time) * self.quantity

    @property
    def total_cost(self):
        return float(self.unit_cost_at_time) * self.quantity

    @property
    def margin(self):
        return self.total_charge - self.total_cost


class Role(Base):
    __tablename__ = "roles"

    id = Column(Integer, primary_key=True)
    name = Column(String, unique=True, nullable=False)
    permissions = Column(Text, default="")   # comma-separated permission keys
    is_admin = Column(Boolean, nullable=False, default=False)  # grants all permissions
    builtin = Column(Boolean, nullable=False, default=False)
    created_at = Column(DateTime, default=datetime.utcnow)


class User(Base):
    __tablename__ = "users"

    id = Column(Integer, primary_key=True)
    username = Column(String, default="")
    email = Column(String, default="", index=True)
    role_id = Column(Integer, ForeignKey("roles.id"), nullable=True)
    active = Column(Boolean, nullable=False, default=True)
    locked = Column(Boolean, nullable=False, default=False)  # role set manually (don't auto-map)
    source = Column(String, default="idp")  # idp | local
    created_at = Column(DateTime, default=datetime.utcnow)

    role = relationship("Role")


class AuditLog(Base):
    __tablename__ = "audit_log"

    id = Column(Integer, primary_key=True)
    created_at = Column(DateTime, default=datetime.utcnow)
    user = Column(String, default="")
    action = Column(String, nullable=False)  # e.g. part.create, sale.checkout
    entity_type = Column(String, default="")
    entity_id = Column(Integer, nullable=True)
    summary = Column(Text, default="")
