from datetime import datetime

from sqlalchemy import (
    Boolean,
    Column,
    DateTime,
    ForeignKey,
    Integer,
    Numeric,
    String,
    Text,
)
from sqlalchemy.orm import relationship

from .database import Base


class Setting(Base):
    """Simple key/value store for UI-configurable settings."""

    __tablename__ = "settings"

    key = Column(String, primary_key=True)
    value = Column(Text, default="")


class Category(Base):
    __tablename__ = "categories"

    id = Column(Integer, primary_key=True)
    name = Column(String, nullable=False)
    description = Column(Text, default="")
    parent_id = Column(Integer, ForeignKey("categories.id"), nullable=True)
    created_at = Column(DateTime, default=datetime.utcnow)

    parent = relationship("Category", remote_side=[id], backref="children")


class Part(Base):
    __tablename__ = "parts"

    id = Column(Integer, primary_key=True)
    name = Column(String, nullable=False)
    description = Column(Text, default="")
    icon = Column(String, default="")  # emoji / short text for quick identification
    barcode = Column(String, unique=True, nullable=False, index=True)
    # "bulk"  -> quantity-tracked SKU, one barcode shared by many identical items
    # "unique"-> a single physical item with its own barcode
    type = Column(String, nullable=False, default="bulk")
    unit_cost = Column(Numeric(10, 2), nullable=False, default=0)   # what the item costs us
    unit_price = Column(Numeric(10, 2), nullable=False, default=0)  # what we charge the client
    quantity_on_hand = Column(Integer, nullable=False, default=0)
    category_id = Column(Integer, ForeignKey("categories.id"), nullable=True)
    # Per-part override; None falls back to the global default threshold.
    low_stock_threshold = Column(Integer, nullable=True)
    low_stock_alerted = Column(Boolean, nullable=False, default=False)
    # True when the barcode was generated by us (printable label available).
    barcode_generated = Column(Boolean, nullable=False, default=False)
    active = Column(Boolean, nullable=False, default=True)
    created_at = Column(DateTime, default=datetime.utcnow)

    category = relationship("Category")


class Client(Base):
    # Table stays "customers" so existing data upgrades in place.
    __tablename__ = "customers"

    id = Column(Integer, primary_key=True)
    name = Column(String, nullable=False)
    reference = Column(String, default="")  # account / customer number
    contact_name = Column(String, default="")
    email = Column(String, default="")
    phone = Column(String, default="")
    location = Column(String, default="")  # site / building / room
    address = Column(Text, default="")
    notes = Column(Text, default="")
    active = Column(Boolean, nullable=False, default=True)
    created_at = Column(DateTime, default=datetime.utcnow)

    jobs = relationship("Job", back_populates="client", order_by="Job.name")


class Job(Base):
    __tablename__ = "jobs"

    id = Column(Integer, primary_key=True)
    client_id = Column(Integer, ForeignKey("customers.id"), nullable=False)
    name = Column(String, nullable=False)
    reference = Column(String, default="")  # ticket / work-order number
    notes = Column(Text, default="")
    active = Column(Boolean, nullable=False, default=True)
    created_at = Column(DateTime, default=datetime.utcnow)

    client = relationship("Client", back_populates="jobs")


class Transaction(Base):
    __tablename__ = "transactions"

    id = Column(Integer, primary_key=True)
    # Column name stays customer_id for data compatibility; it points at a Client.
    customer_id = Column(Integer, ForeignKey("customers.id"), nullable=False)
    job_id = Column(Integer, ForeignKey("jobs.id"), nullable=True)
    part_id = Column(Integer, ForeignKey("parts.id"), nullable=False)
    quantity = Column(Integer, nullable=False, default=1)
    # Snapshots taken at charge-out time so later price edits never rewrite history.
    unit_cost_at_time = Column(Numeric(10, 2), nullable=False, default=0)   # our cost
    unit_price_at_time = Column(Numeric(10, 2), nullable=False, default=0)  # client charge
    scanned_by = Column(String, default="")
    note = Column(Text, default="")
    voided = Column(Boolean, nullable=False, default=False)
    created_at = Column(DateTime, default=datetime.utcnow)

    part = relationship("Part")
    client = relationship("Client", foreign_keys=[customer_id])
    job = relationship("Job", foreign_keys=[job_id])

    @property
    def total_charge(self):
        return float(self.unit_price_at_time) * self.quantity

    @property
    def total_cost(self):
        return float(self.unit_cost_at_time) * self.quantity

    @property
    def margin(self):
        return self.total_charge - self.total_cost


class AuditLog(Base):
    __tablename__ = "audit_log"

    id = Column(Integer, primary_key=True)
    created_at = Column(DateTime, default=datetime.utcnow)
    user = Column(String, default="")
    action = Column(String, nullable=False)  # e.g. part.create, sale.checkout
    entity_type = Column(String, default="")
    entity_id = Column(Integer, nullable=True)
    summary = Column(Text, default="")
